global:
  variables:
  - DATABASE_URL=postgres://root:secret@localhost/docker
  - RAILS_ENV=test
  runner:
    os_image: ubuntu
    
tasks:
  rspec:
    runner:
      os_image: ubuntu
      containers:
      - image: postgres:9.6
        environment:
        - POSTGRES_DB=docker
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
    steps:
    - checkout
    - cache/pull: bundle-{{ checksum "Gemfile.lock" }}
    - commands:
      - gem install bundler:1.17.3
      - bundle --version
    - run: bundle install --path vendor/bundle || bundle check
    - commands:
      - dockerize -wait tcp://localhost:5432 -timeout 30s
      - bundle exec rspec
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]
    
  build:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/RazorOp/rails-sample-app
        dockerfile: Dockerfile
        tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
        push: true