version: v2
global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/razorops-public/rails-sample-app/rails-app
        push: true
        tags: ["${CI_COMMIT_SHA}", "latest"]
        dockerfile: Dockerfile
        context: .