tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: registry.digitalocean.com/test-demo/test-demo
        tags: ["${CI_COMMIT_SHA}", "latest", "${CI_REPO_BRANCH}"]
        push: true