tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: test-demo
        tags: ["${CI_COMMIT_SHA:0:8}", "latest", "${CI_REPO_BRANCH}"]
    - commands:
      - bundle exec rake test
    - reports/html: 
        dir: coverage
        index: index.html
