global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/RazorOp/rails-sample-app
        push: true
        tags: ["${CI_COMMIT_SHA}", "latest"]
        dockerfile: Dockerfile
        context: .