global:
  variables:
  - DATABASE_URL=postgres://root:secret@localhost/docker
  - RAILS_ENV=test
  runner:
    os_image: ubuntu
    
tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/RazorOp/rails-sample-app
        dockerfile: Dockerfile
        tags: ["latest", "${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}"]
        push: true